name: Build (Windows)

on:
  push:
    branches: [ "*" ]
    paths:
      - .github/workflows/build-windows.yml
      - src/**
      - xmake.lua
  workflow_dispatch:

env:
  BUILD_PLATFORM: windows
  BUILD_ARCHITECTURE: x64

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
      
      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ env.BUILD_PLATFORM }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-${{ env.BUILD_PLATFORM }}-
    
      - name: Configure
        run: |
          xmake f -a ${{ env.BUILD_ARCHITECTURE }} -m ${{ matrix.mode }} -p ${{ env.BUILD_PLATFORM }} -v -y
    
      - name: Build
        run: |
          xmake -v -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: restore-mtime-${{ matrix.mode }}-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_ARCHITECTURE }}-${{ github.sha }}
          path: |
            build/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_ARCHITECTURE }}/${{ matrix.mode }}
