name: Build (Linux)

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - name: Chechout
        uses: actions/checkout@v4

      - name: Setup build environment 
        run: |
          sudo apt install -y build-essential
        
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
     
      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-linux-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-
     
      - name: Configure
        run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p linux -v -y
    
      - name: Build
        run: |
          xmake -v -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: restore-mtime-${{ matrix.mode }}-linux-x64-${{ github.sha }}
          path: |
            build/linux/x64/${{ matrix.mode }}