name: Build (Linux)

on:
  push:
    branches: [ "*" ]
    paths:
      - .github/workflows/build-linux.yml
      - src/**
      - xmake.lua

env:
  BUILD_GCC_VERSION: 14
  
  BUILD_PLATFORM: linux
  BUILD_ARCHITECTURE: x64

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - name: Chechout
        uses: actions/checkout@v4

      - name: Setup GCC
        run: |
          echo "deb http://archive.ubuntu.com/ubuntu noble main universe" | sudo tee /etc/apt/sources.list.d/noble.list
          sudo apt update
          sudo apt install gcc-$BUILD_GCC_VERSION g++-$BUILD_GCC_VERSION
        
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
     
      - name: Restore xmake cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-${{ env.BUILD_PLATFORM }}-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-${{ env.BUILD_PLATFORM }}-
     
      - name: Configure
        run: |
          xmake f -a ${{ env.BUILD_ARCHITECTURE }} -m ${{ matrix.mode }} -p ${{ env.BUILD_PLATFORM }} --toolchain=gcc-$BUILD_GCC_VERSION -v -y
    
      - name: Build
        run: |
          xmake -v -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: restore-mtime-${{ matrix.mode }}-${{ env.BUILD_PLATFORM }}-x64-${{ github.sha }}
          path: |
            build/${{ env.BUILD_PLATFORM }}/${{ env.BUILD_ARCHITECTURE }}/${{ matrix.mode }}
